version: "3"
services:
  database:
    image: postgres:latest
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
      - ./schema.sh:/docker-entrypoint-initdb.d/schema.sh
